<?php
require_once '../../includes/auth_check.php';
require_once '../../config/db.php';
include_once '../../includes/header.php';
include_once '../../includes/navbar.php';
require_once '../../includes/sidebar.php';

// Only admin can access
if ($_SESSION['user']['role'] !== 'admin') {
    echo "<p style='color:red; padding-left:200px; padding-top:50px;'>Access denied. Only admins can access this page.</p>";
    include_once '../../includes/footer.php';
    exit;
}


$start = $_GET['start'] ?? date('Y-m-d');
$end   = $_GET['end'] ?? date('Y-m-d');

if (!$start || !$end) {
    echo "<p>Please select a valid date range.</p>";
    include_once '../../includes/footer.php';
    exit;
}

// Manual expenses
$sql = "SELECT id, title, amount, expense_date
        FROM expenses
        WHERE DATE(expense_date) BETWEEN ? AND ?
        ORDER BY expense_date ASC";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $start, $end);
$stmt->execute();
$manualExpenses = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);

// Ingredient Stock Cost
$stockSql = "SELECT COALESCE(SUM(isl.quantity_added * COALESCE(i.cost_per_unit, 0)), 0) AS total_stock_cost
             FROM ingredient_stock_log isl
             INNER JOIN ingredients i ON i.id = isl.ingredient_id
             WHERE DATE(isl.added_at) BETWEEN ? AND ?";
$stockStmt = $conn->prepare($stockSql);
$stockStmt->bind_param("ss", $start, $end);
$stockStmt->execute();
$stockCost = (float)($stockStmt->get_result()->fetch_assoc()['total_stock_cost'] ?? 0);

// Employee Salaries
$salarySql = "SELECT COALESCE(SUM(salary), 0) AS total_salaries FROM employees";
$salaryRes = $conn->query($salarySql);
$salaryCost = (float)($salaryRes->fetch_assoc()['total_salaries'] ?? 0);

// Merge and calculate total
$expenseData = [];
$expenseData[] = ['id' => '-', 'expense_date' => $start, 'title' => 'Ingredient Stock Cost', 'amount' => $stockCost];
$expenseData[] = ['id' => '-', 'expense_date' => $start, 'title' => 'Employee Salaries', 'amount' => $salaryCost];
$expenseData = array_merge($expenseData, $manualExpenses);

$totalExpense = $stockCost + $salaryCost;
foreach ($manualExpenses as $row) {
    $totalExpense += $row['amount'];
}
?>

<style>
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #bfc3ccc8; margin: 0; padding-top: 40px; padding-left: 170px; padding-right: 30px; }
    .top-header { text-align: center; margin-top: 20px; margin-bottom: 10px; }
    .top-header img { height: 50px; vertical-align: middle; }
    .top-header h1 { display: inline-block; margin-left: 10px; font-size: 32px; color: #ff4500; vertical-align: middle; }

    .container { max-width: 1100px; margin: 30px auto; background: #fff; padding: 20px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }
    h2 { margin-top: 0; color: #333; }

    table { width: 100%; border-collapse: collapse; font-size: 16px; margin-top: 10px; }
    thead th { background: #ff4500; color: #fff; text-align: left; padding: 10px; }
    tbody td { border-bottom: 1px solid #eee; padding: 10px; vertical-align: middle; }
    tr:nth-child(even) { background: #f9f9f9; }

    .totals { margin: 15px 0; display: flex; gap: 20px; flex-wrap: wrap; }
    .total-card { flex: 1; min-width: 200px; background: #f5f5f5; padding: 15px; border-radius: 8px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
    .total-card h4 { margin: 0; font-size: 18px; color: #333; }
    .total-card p { margin: 5px 0 0; font-size: 20px; font-weight: bold; color: #ff4500; }

    .btn { padding: 8px 14px; border-radius: 6px; font-size: 14px; text-decoration: none; margin-right: 8px; }
    .btn-danger { background: #dc3545; color: #fff; }
    .btn-danger:hover { background: #b02a37; }
    .btn-secondary { background: #6c757d; color: #fff; }
    .btn-secondary:hover { background: #565e64; }
</style>

<!-- Header -->
<div class="top-header">
    <img src="../../assets/images/logo.png" alt="Logo">
    <h1>Hot Slice Pizza</h1>
</div>

<div class="container">
    <h2>Expense Report</h2>
    <p><strong>Date Range:</strong> <?= htmlspecialchars($start) ?> to <?= htmlspecialchars($end) ?></p>
    <p><strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['user']['username']) ?></p>

    <!-- Totals -->
    <div class="totals">
        <div class="total-card">
            <h4>Total Expenses</h4>
            <p>Rs. <?= number_format($totalExpense, 2) ?></p>
        </div>
    </div>

    <hr>

    <h4>Expense Records</h4>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Title</th>
                <th>Amount (Rs.)</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($expenseData) > 0): ?>
                <?php foreach ($expenseData as $exp): ?>
                    <tr>
                        <td><?= $exp['id'] ?></td>
                        <td><?= $exp['expense_date'] ?></td>
                        <td><?= htmlspecialchars($exp['title']) ?></td>
                        <td><?= number_format($exp['amount'], 2) ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="4" style="text-align:center;">No expenses found for this range.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>
    <br>

    <div class="mt-3">
        <a href="../../controllers/reports_range.php?download_pdf=1&type=Expenses&start=<?= $start ?>&end=<?= $end ?>" class="btn btn-danger">Download PDF</a>
        <a href="index.php" class="btn btn-secondary">← Back to Reports Dashboard</a>
    </div>
</div>

<?php include_once '../../includes/footer.php'; ?>
