<?php
require_once '../../includes/auth_check.php';
require_once '../../config/db.php';
include_once '../../includes/header.php';
require_once '../../includes/sidebar.php';

// Only admin can access
if ($_SESSION['user']['role'] !== 'admin') {
    echo "<p style='color:red; padding-left:200px; padding-top:50px;'>Access denied. Only admins can access this page.</p>";
    include_once '../../includes/footer.php';
    exit;
}


$start = $_GET['start'] ?? date('Y-m-d');
$end   = $_GET['end'] ?? date('Y-m-d');

if (!$start || !$end) {
    echo "<p>Please select a valid date range.</p>";
    include_once '../../includes/footer.php';
    exit;
}

// Fetch Sales Data
$sql = "
    SELECT id, total_price, payment_method, order_type, created_at AS sale_date
    FROM sales
    WHERE DATE(created_at) BETWEEN ? AND ?
    ORDER BY created_at ASC
";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $start, $end);
$stmt->execute();
$result = $stmt->get_result();

// Totals
$totalCash = 0;
$totalOnline = 0;
$totalAll = 0;
$salesData = [];

while ($row = $result->fetch_assoc()) {
    if (strtolower(trim($row['payment_method'])) === 'cash') {
        $totalCash += $row['total_price'];
    } else {
        $totalOnline += $row['total_price'];
    }
    $totalAll += $row['total_price'];
    $salesData[] = $row;
}
?>
<style>
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #bfc3ccc8; margin: 0; padding-top: 40px; padding-left: 170px; padding-right: 30px; }
    .top-header { text-align: center; margin-top: 20px; margin-bottom: 10px; }
    .top-header img { height: 50px; vertical-align: middle; }
    .top-header h1 { display: inline-block; margin-left: 10px; font-size: 32px; color: #ff4500; vertical-align: middle; }

    .container { max-width: 1100px; margin: 30px auto; background: #fff; padding: 20px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }
    h2 { margin-top: 0; color: #333; }

    table { width: 100%; border-collapse: collapse; font-size: 16px; margin-top: 10px; }
    thead th { background: #ff4500; color: #fff; text-align: left; padding: 10px; }
    tbody td { border-bottom: 1px solid #eee; padding: 10px; vertical-align: middle; }
    tr:nth-child(even) { background: #f9f9f9; }

    .totals { margin: 15px 0; display: flex; gap: 20px; flex-wrap: wrap; }
    .total-card { flex: 1; min-width: 200px; background: #f5f5f5; padding: 15px; border-radius: 8px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
    .total-card h4 { margin: 0; font-size: 18px; color: #333; }
    .total-card p { margin: 5px 0 0; font-size: 20px; font-weight: bold; color: #ff4500; }
    .btn-danger { background: #dc3545; color: #fff; }
    .btn-danger:hover { background: #b02a37; }
    .btn-secondary { background: #6c757d; color: #fff; }
    .btn-secondary:hover { background: #565e64; }
</style>

<!-- Header -->
<div class="top-header">
    <img src="../../assets/images/logo.png" alt="Logo">
    <h1>Hot Slice Pizza</h1>
</div>

<div class="container">
    <h2>Sales Report (<?= htmlspecialchars($start) ?> → <?= htmlspecialchars($end) ?>)</h2>
    <p><strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['user']['username']) ?></p>

    <!-- Totals -->
    <div class="totals">
        <div class="total-card">
            <h4>Cash Sales</h4>
            <p>Rs. <?= number_format($totalCash, 2) ?></p>
        </div>
        <div class="total-card">
            <h4>Online Sales</h4>
            <p>Rs. <?= number_format($totalOnline, 2) ?></p>
        </div>
        <div class="total-card">
            <h4>Total Sales</h4>
            <p>Rs. <?= number_format($totalAll, 2) ?></p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Order Type</th>
                <th>Payment Method</th>
                <th>Total Price (Rs.)</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($salesData) > 0): ?>
                <?php foreach ($salesData as $sale): ?>
                    <tr>
                        <td><?= $sale['id'] ?></td>
                        <td><?= $sale['sale_date'] ?></td>
                        <td><?= htmlspecialchars($sale['order_type']) ?></td>
                        <td><?= htmlspecialchars($sale['payment_method']) ?></td>
                        <td><?= number_format($sale['total_price'], 2) ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="5" style="text-align:center;">No sales found for this range.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="mt-3" style="margin-top:20px;">
        <a href="../../controllers/reports_range.php?download_pdf=1&type=Sales&start=<?= $start ?>&end=<?= $end ?>" class="btn btn-danger">Download PDF</a>
        <a href="index.php" class="btn btn-secondary">← Back to Reports Dashboard</a>
    </div>
</div>

<?php include_once '../../includes/footer.php'; ?>
