<?php
require_once '../../includes/auth_check.php';
require_once '../../config/db.php';
include_once '../../includes/header.php';
include_once '../../includes/navbar.php';
require_once '../../includes/sidebar.php';

// Only admin can access
if ($_SESSION['user']['role'] !== 'admin') {
    echo "<p style='color:red; padding-left:200px; padding-top:50px;'>Access denied. Only admins can access this page.</p>";
    include_once '../../includes/footer.php';
    exit;
}


$start = $_GET['start'] ?? date('Y-m-d');
$end   = $_GET['end'] ?? date('Y-m-d');

if (!$start || !$end) {
    echo "<p>Please select a valid date range.</p>";
    include_once '../../includes/footer.php';
    exit;
}

$sql = "SELECT isl.id, i.id AS ingredient_id, i.name AS ingredient_name, isl.quantity_added, 
               i.cost_per_unit, isl.added_at, u.base_unit, u.unit_name
        FROM ingredient_stock_log isl
        JOIN ingredients i ON isl.ingredient_id = i.id
        JOIN units u ON i.unit_id = u.id
        WHERE DATE(isl.added_at) BETWEEN ? AND ?
        ORDER BY isl.added_at ASC";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $start, $end);
$stmt->execute();
$result = $stmt->get_result();

$totalQuantity = 0;
$totalCost = 0;
$stockData = [];
$groupedData = [];

while ($row = $result->fetch_assoc()) {
    $row['total_cost'] = $row['quantity_added'] * $row['cost_per_unit'];
    $totalQuantity += $row['quantity_added'];
    $totalCost += $row['total_cost'];
    $stockData[] = $row;

    $id = $row['ingredient_id'];
    if (!isset($groupedData[$id])) {
        $groupedData[$id] = [
            'name' => $row['ingredient_name'],
            'unit_name' => $row['unit_name'],
            'total_qty' => 0,
            'total_cost' => 0
        ];
    }
    $groupedData[$id]['total_qty'] += $row['quantity_added'];
    $groupedData[$id]['total_cost'] += $row['total_cost'];
}

// Usage
$usageSql = "SELECT ingredient_id, COALESCE(SUM(quantity_used),0) AS used_qty
             FROM ingredient_usage_logs
             GROUP BY ingredient_id";
$usageRes = $conn->query($usageSql);
$usageData = [];
while ($u = $usageRes->fetch_assoc()) {
    $usageData[$u['ingredient_id']] = $u['used_qty'];
}
foreach ($groupedData as $id => &$ing) {
    $used = $usageData[$id] ?? 0;
    $ing['remaining_qty'] = $ing['total_qty'] - $used;
}
?>
<style>
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #bfc3ccc8; padding-top: 40px; padding-left: 170px; padding-right: 30px; }
    .top-header { text-align: center; margin: 20px 0; }
    .top-header img { height: 50px; vertical-align: middle; }
    .top-header h1 { display: inline-block; margin-left: 10px; font-size: 32px; color: #ff4500; vertical-align: middle; }
    .container { max-width: 1100px; margin: 30px auto; background: #fff; padding: 20px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }
    h2 { color: #333; }
    table { width: 100%; border-collapse: collapse; font-size: 16px; margin-top: 10px; }
    thead th { background: #ff4500; color: #fff; padding: 10px; text-align: left; } /* 👈 Header text aligned right */
    tbody td { border-bottom: 1px solid #eee; padding: 10px; }
    tr:nth-child(even) { background: #f9f9f9; }
    .totals { display: flex; gap: 20px; margin: 15px 0; }
    .total-card { flex: 1; background: #f5f5f5; padding: 15px; border-radius: 8px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
    .total-card h4 { margin: 0; font-size: 18px; }
    .total-card p { margin: 5px 0 0; font-size: 20px; font-weight: bold; color: #ff4500; }
    .btn { padding: 8px 14px; border-radius: 6px; font-size: 14px; text-decoration: none; margin-right: 8px; }
    .btn-danger { background: #dc3545; color: #fff; }
    .btn-danger:hover { background: #b02a37; }
    .btn-secondary { background: #6c757d; color: #fff; }
    .btn-secondary:hover { background: #565e64; }
</style>

<div class="top-header">
    <img src="../../assets/images/logo.png" alt="Logo">
    <h1>Hot Slice Pizza</h1>
</div>

<div class="container">
    <h2>Stock Added Report</h2>
    <p><strong>Date Range:</strong> <?= htmlspecialchars($start) ?> to <?= htmlspecialchars($end) ?></p>
    <p><strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['user']['username']) ?></p>
    <p><strong>Total Cost of All Ingredients:</strong> Rs <?= number_format($totalCost, 2) ?></p>

    <div class="totals">
        <div class="total-card"><h4>Total Quantity Added</h4><p><?= number_format($totalQuantity, 2) ?></p></div>
        <div class="total-card"><h4>Total Cost</h4><p>Rs <?= number_format($totalCost, 2) ?></p></div>
    </div>

    <hr>
    <h4>Stock Addition Records</h4>
    <table>
        <thead>
            <tr><th>ID</th><th>Date</th><th>Ingredient</th><th>Quantity</th><th>Base Unit</th><th>Unit Cost (Rs.)</th><th>Total Cost (Rs.)</th></tr>
        </thead>
        <tbody>
            <?php if ($stockData): foreach ($stockData as $st): ?>
                <tr>
                    <td><?= $st['id'] ?></td>
                    <td><?= $st['added_at'] ?></td>
                    <td><?= htmlspecialchars($st['ingredient_name']) ?></td>
                    <td><?= number_format($st['quantity_added'], 2) ?></td>
                    <td><?= $st['base_unit'] ?></td>
                    <td><?= number_format($st['cost_per_unit'], 2) ?></td>
                    <td><?= number_format($st['total_cost'], 2) ?></td>
                </tr>
            <?php endforeach; else: ?>
                <tr><td colspan="7" style="text-align:center;">No stock additions found for this range.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <hr>
    <h4>Ingredient-wise Summary</h4>
    <table>
        <thead>
            <tr><th>Ingredient</th><th>Total Quantity</th><th>Remaining Quantity</th><th>Unit</th><th>Total Cost (Rs.)</th></tr>
        </thead>
        <tbody>
            <?php foreach ($groupedData as $ing): ?>
                <tr>
                    <td><?= htmlspecialchars($ing['name']) ?></td>
                    <td><?= number_format($ing['total_qty'], 2) ?></td>
                    <td><?= number_format($ing['remaining_qty'], 2) ?></td>
                    <td><?= $ing['unit_name'] ?></td>
                    <td><?= number_format($ing['total_cost'], 2) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <br>
    <div>
        <a href="../../controllers/reports_range.php?download_pdf=1&type=Stock_added&start=<?= $start ?>&end=<?= $end ?>" class="btn btn-danger">Download PDF</a>
        <a href="index.php" class="btn btn-secondary">← Back to Reports Dashboard</a>
    </div>
</div>
<?php include_once '../../includes/footer.php'; ?>
