<?php
require_once '../../includes/auth_check.php';
require_once '../../config/db.php';
include_once '../../includes/header.php';
include_once '../../includes/navbar.php';
require_once '../../includes/sidebar.php';

// Only admin can access
if ($_SESSION['user']['role'] !== 'admin') {
    echo "<p style='color:red; padding-left:200px; padding-top:50px;'>Access denied. Only admins can access this page.</p>";
    include_once '../../includes/footer.php';
    exit;
}


$start = $_GET['start'] ?? date('Y-m-d');
$end   = $_GET['end'] ?? date('Y-m-d');

if (!$start || !$end) {
    echo "<p>Please select a valid date range.</p>";
    include_once '../../includes/footer.php';
    exit;
}

$sql = "
    SELECT l.id, i.id AS ingredient_id, i.name AS ingredient_name, l.quantity_used, l.cost, l.used_at, l.sale_id,
           u.base_unit, u.unit_name
    FROM ingredient_usage_logs l
    JOIN ingredients i ON l.ingredient_id = i.id
    JOIN units u ON i.unit_id = u.id
    WHERE DATE(l.used_at) BETWEEN ? AND ?
    ORDER BY l.used_at ASC
";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $start, $end);
$stmt->execute();
$result = $stmt->get_result();

$totalQuantity = 0;
$totalCost = 0;
$usageData = [];
$groupedData = [];

while ($row = $result->fetch_assoc()) {
    $totalQuantity += $row['quantity_used'];
    $totalCost += $row['cost'];
    $usageData[] = $row;

    $id = $row['ingredient_id'];
    if (!isset($groupedData[$id])) {
        $groupedData[$id] = [
            'name' => $row['ingredient_name'],
            'unit_name' => $row['unit_name'],
            'used_qty' => 0,
            'total_cost' => 0
        ];
    }
    $groupedData[$id]['used_qty'] += $row['quantity_used'];
    $groupedData[$id]['total_cost'] += $row['cost'];
}

// Fetch Stock Added for Remaining
$stockSql = "SELECT ingredient_id, SUM(quantity_added) AS total_added
             FROM ingredient_stock_log
             WHERE DATE(added_at) BETWEEN ? AND ?
             GROUP BY ingredient_id";
$stockStmt = $conn->prepare($stockSql);
$stockStmt->bind_param("ss", $start, $end);
$stockStmt->execute();
$stockRes = $stockStmt->get_result();
$stockAdded = [];
while ($s = $stockRes->fetch_assoc()) {
    $stockAdded[$s['ingredient_id']] = $s['total_added'];
}

foreach ($groupedData as $id => &$g) {
    $added = $stockAdded[$id] ?? 0;
    $g['remaining_qty'] = $added - $g['used_qty'];
}
?>

<style>
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #bfc3ccc8; padding-top: 40px; padding-left: 170px; padding-right: 30px; }
    .top-header { text-align: center; margin: 20px 0; }
    .top-header img { height: 50px; vertical-align: middle; }
    .top-header h1 { display: inline-block; margin-left: 10px; font-size: 32px; color: #ff4500; vertical-align: middle; }
    .container { max-width: 1100px; margin: 30px auto; background: #fff; padding: 20px; border-radius: 12px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }
    h2 { color: #333; }
    table { width: 100%; border-collapse: collapse; font-size: 16px; margin-top: 10px; }
    thead th { background: #ff4500; color: #fff; padding: 10px; text-align: right; }
    tbody td { border-bottom: 1px solid #eee; padding: 10px; text-align: right; }
    tr:nth-child(even) { background: #f9f9f9; }
    .totals { display: flex; gap: 20px; margin: 15px 0; }
    .total-card { flex: 1; background: #f5f5f5; padding: 15px; border-radius: 8px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
    .total-card h4 { margin: 0; font-size: 18px; }
    .total-card p { margin: 5px 0 0; font-size: 20px; font-weight: bold; color: #ff4500; }
    .btn { padding: 8px 14px; border-radius: 6px; font-size: 14px; text-decoration: none; margin-right: 8px; }
    .btn-danger { background: #dc3545; color: #fff; }
    .btn-danger:hover { background: #b02a37; }
    .btn-secondary { background: #6c757d; color: #fff; }
    .btn-secondary:hover { background: #565e64; }
</style>

<div class="top-header">
    <img src="../../assets/images/logo.png" alt="Logo">
    <h1>Hot Slice Pizza</h1>
</div>

<div class="container">
    <h2>Stock Usage Report</h2>
    <p><strong>Date Range:</strong> <?= htmlspecialchars($start) ?> to <?= htmlspecialchars($end) ?></p>
    <p><strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['user']['username']) ?></p>

    <div class="totals">
        <div class="total-card">
            <h4>Total Quantity Used</h4>
            <p><?= number_format($totalQuantity, 2) ?></p>
        </div>
        <div class="total-card">
            <h4>Total Usage Cost</h4>
            <p>Rs <?= number_format($totalCost, 2) ?></p>
        </div>
    </div>

    <hr>
    <h4>Stock Usage Records</h4>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Ingredient</th>
                <th>Quantity Used</th>
                <th>Base Unit</th>
                <th>Cost (Rs.)</th>
                <th>Sale ID</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($usageData) > 0): ?>
                <?php foreach ($usageData as $us): ?>
                    <tr>
                        <td><?= $us['id'] ?></td>
                        <td><?= $us['used_at'] ?></td>
                        <td style="text-align:left;"><?= htmlspecialchars($us['ingredient_name']) ?></td>
                        <td><?= number_format($us['quantity_used'], 2) ?></td>
                        <td><?= $us['base_unit'] ?></td>
                        <td><?= number_format($us['cost'], 2) ?></td>
                        <td><?= $us['sale_id'] ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="7" style="text-align:center;">No stock usage found for this range.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <hr>
    <h4>Ingredient-wise Summary</h4>
    <table>
        <thead>
            <tr>
                <th>Ingredient</th>
                <th>Total Used Quantity</th>
                <th>Remaining Quantity</th>
                <th>Unit</th>
                <th>Total Cost (Rs.)</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($groupedData as $ing): ?>
                <tr>
                    <td style="text-align:left;"><?= htmlspecialchars($ing['name']) ?></td>
                    <td><?= number_format($ing['used_qty'], 2) ?></td>
                    <td><?= number_format($ing['remaining_qty'], 2) ?></td>
                    <td><?= $ing['unit_name'] ?></td>
                    <td><?= number_format($ing['total_cost'], 2) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <br>
    <div>
        <a href="../../controllers/reports_range.php?download_pdf=1&type=Stock_usage&start=<?= $start ?>&end=<?= $end ?>" class="btn btn-danger">Download PDF</a>
        <a href="index.php" class="btn btn-secondary">← Back to Reports Dashboard</a>
    </div>
</div>

<?php include_once '../../includes/footer.php'; ?>
